config:
    - health-canary: "health-check-monitor.json"
  
health-canary:
    - name: "webcheck.simplenode.canary"
    - url: "http://simplenodeservice.canary.{{ .Env.INGRESS_DOMAIN }}/api/invoke?url=https://www.dynatrace.com"
    - description: "Health Check for simplenode in canary"
    - location: "/infrastructure/synthetic-location/acebox.id"
    # - managementZoneId: "/ace/management-zone/management-zone-staging.id"
    - tag: "/ace/auto-tag/tagging-canary.name"
    #- applicationId: "/ace/application/app-simplenode-staging.id"
    - enabled: "true"
